version: '3.4'

services:
  extractor:
    image: oeh-search-meta:latest
    ports:
      - "5057:5057"
    links:
      - splash
      - accessibility
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5057/_ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
  splash:
    image: scrapinghub/splash:master
    command: --maxrss 4000
    restart: always
    expose:
      - "8050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/_ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
  accessibility:
    image: oeh-search-meta_lighthouse:latest
    restart: always
    expose:
      - "5058"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5058/_ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    networks:
      - backend
networks:
  backend:
