version: '3'

services:
  extractor:
    image: oeh-search-meta:latest
    ports:
      - "5057:5057"
    healthcheck:
      test: curl --fail -s http://localhost:5057/hello || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3