[tool.poetry]
name = "oeh-search-meta"
version = "0.1.0"
description = ""
authors = ["Robert Meissner <robert.meissner@codecentric.de>"]

[tool.poetry.dependencies]
python = "^3.9.0rc1"
fastapi = "^0.61.1"
uvicorn = "^0.12.2"
requests = "^2.24.0"
bs4 = "^0.0.1"
adblockparser = "^0.7"
lxml = "^4.6.1"
tldextract = "^3.0.2"

[tool.poetry.dev-dependencies]
pylint = "^2.6.0"
pre-commit = "^2.8.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
pandas = "^1.1.4"
altair = "^4.1.0"
altair-viewer = "^0.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.venv
  | logs
  | src\logs
)/
'''

[tool.pytest]
testpaths = "tests"