name: Metadata Extractor Docker Image

on:
  push:
    branches: main

jobs:

  build:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: codecentric/metadata_picker/oeh-search-meta
          tags: codecentric/metadata_picker/oeh-search-meta_meta:latest
